server:
  port: 8081
spring:
  # 机器人配置
  bot:
    # 插件列表，有序
    plugin-list:
      - com.xuyang9978.ktqqbot.plugin.LogPlugin
      - com.xuyang9978.ktqqbot.plugin.RandomPoemPlugin
  # 配置 MySQL 连接信息
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/db_kt_qq_bot?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: xuyang
    password: 12345
  # redis 配置
  redis:
    host: 127.0.0.1
    port: 6379
  # jpa 配置
  jpa:
    # 显示自动生成的sql语句
    show-sql: false
    # Hibernate 根据给定的实体类结构更改数据库中映射的表
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
